//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFinalProjectNiraj2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle_model
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicle_model()
        {
            this.vehicles = new HashSet<vehicle>();
        }
    
        public int vehicle_model_id { get; set; }
        public Nullable<double> engine_size { get; set; }
        public Nullable<int> number_of_doors { get; set; }
        public string colour { get; set; }
        public Nullable<int> vehicle_type_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehicle> vehicles { get; set; }
        public virtual vehicle_type vehicle_type { get; set; }
    }
}
