//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFinalProjectNiraj2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        public int vehicle_id { get; set; }
        public int make_id { get; set; }
        public int vehicle_model_id { get; set; }
        public Nullable<int> manufature_year { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<System.DateTime> sold_date { get; set; }
    
        public virtual make make { get; set; }
        public virtual vehicle_model vehicle_model { get; set; }
    }
}
